sonar.projectKey=juangutierrez1-cai_Proyecto
sonar.organization=juangutierrez1-cai
sonar.host.url=https://sonarcloud.io
sonar.login=cf1e2bf97fa8ef7ef9ef3d8e3d5022caaa

sonar.sources=scr
sonar.language=py
sonar.sourceEncoding=UTF-8
